sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - udf_coverage
      - jar_artifact
build:
  runnerOs: ubuntu-20.04
  freeDiskSpace: false
  exasolDbVersions:
    - "8.24.0"
    - "7.1.26"
  workflows:
    - name: ci-build.yml
      stepCustomizations:
        - action: INSERT_AFTER
          stepId: enable-testcontainer-reuse
          content:
            name: Configure Azure credentials
            id: configure-azure-credentials
            run: echo "$ABS_CS" > abs-cs.json
            env:
              ABS_CS: ${{ secrets.ABS_CS }}
