sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - udf_coverage
      - jar_artifact
excludes:
  - "E-PK-CORE-17: Missing required file: 'release_config.yml'"
build:
  runnerOs: ubuntu-20.04
  freeDiskSpace: false
  exasolDbVersions:
    - "8.27.0" # 8.29.1 not yet supported by exasol-testcontainers, see https://github.com/exasol/exasol-testcontainers/issues/258
    - "7.1.26" # Upgrade to 7.1.29 once https://github.com/exasol/virtual-schema-common-document-files/issues/169 is fixed
  workflows:
    - name: ci-build.yml
      stepCustomizations:
        - action: INSERT_AFTER
          stepId: enable-testcontainer-reuse
          content:
            name: Configure Azure credentials
            id: configure-azure-credentials
            run: echo "$ABS_CS" > abs-cs.json
            env:
              ABS_CS: ${{ secrets.ABS_CS }}
