sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - udf_coverage
      - jar_artifact
build:
  runnerOs: ubuntu-latest # Exasol 7.1.x does not yet support the latest Ubuntu version
  exasolDbVersions:
    - "8.34.0"
    # - "7.1.30" # Exasol 7.1.x does not yet support the latest Ubuntu version
  workflows:
    - name: ci-build.yml
      stepCustomizations:
        - action: INSERT_AFTER
          job: matrix-build
          stepId: enable-testcontainer-reuse
          content:
            name: Configure Azure credentials
            id: configure-azure-credentials
            run: echo "$ABS_CS" > abs-cs.json
            env:
              ABS_CS: ${{ secrets.ABS_CS }}
        - action: INSERT_AFTER
          job: matrix-build
          stepId: enable-testcontainer-reuse
          content:
            name: Fix VM Crash in UDFs
            id: fix-vm-crash
            run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
