sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - udf_coverage
      - jar_artifact
build:
  runnerOs: ubuntu-20.04
  freeDiskSpace: false
  exasolDbVersions:
    - "8.24.0"
    - "7.1.25"
excludes:
  # Configure Azure credentials
  - "E-PK-CORE-18: Outdated content: '.github/workflows/ci-build.yml'"
