sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - udf_coverage
      - jar_artifact
excludes:
  - "E-PK-CORE-18: Outdated content: '.github/workflows/ci-build.yml'"
  - "E-PK-CORE-18: Outdated content: '.github/workflows/release_droid_prepare_original_checksum.yml'"
build:
  runnerOs: ubuntu-20.04
  freeDiskSpace: false
  exasolDbVersions:
    - "7.1.24"
